[project]
name = "pathfinder-god-hub-client"
version = "0.1.0"
description = "A client library for accessing Pathfinder God Hub"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.23.1,<0.29.0",
    "attrs>=22.2.0",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["pathfinder_god_hub_client*"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["F", "I", "UP"]